/**:
  ros__parameters:
    pseudo_jerk_weight: 10.0 # weight for "smoothness" cost
    over_v_weight: 100.0   # weight for "over speed limit" cost
    over_a_weight: 50.0     # weight for "over accel limit" cost
