/**:
  ros__parameters:
  # Ioniq5 in MORAI
    wheel_radius: 0.383 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.255 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 3.0 # between front wheel center and rear wheel center
    wheel_tread: 1.64 # between left wheel center and right wheel center
    front_overhang: 0.845 # between front wheel center and vehicle front
    rear_overhang: 0.79 # between rear wheel center and vehicle rear
    left_overhang: 0.128 # between left wheel center and vehicle left
    right_overhang: 0.128 # between right wheel center and vehicle right
    vehicle_height: 2.434
    max_steer_angle: 0.69 # [rad]
